// MyLocale.dart
import 'package:get/get.dart';

class MyLocaleEn extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {"1": "Home", "2": "About", "3": "Settings" , "4":"Dark mode" , "5":"Languages" , "6":"Profil" , "7":"Availability" , "8":"All Appointment" , "9":"Logout" ,"10":"Update" , "11":"Address" , "12":"Phone" ,"13":"Full Name" , "14":"Today availablity","15":"Add Appointment" , "16":"Selected Hours" , "17":"Selected Day" , "18":"Login" ,"19":"Enter your email" , "20":"Enter your password" , "21":"Forgot your password?" , "22":"Don't have an account?" , "23":"Sign Up" , "24":"Enter your Phone" , "25":"Enter your adress" , "26":"Enter your speciality" , "27":"Enter your full name" , "28":"Already have an account?" , "29":"create account" , "30":"Reset Password" , "31":"Login to enjoy the features we've \nprovided, and stay healthy" , "32":"Lets get Started!" , "33":"Tomorrow availablity"  , "34":"Date" , "35":"Hour" ,"36":" full name" ,"37":"Email" ,"38":"Patient phone" , "39":"Today Appointments","39":"Update Profile","40":"Are you sure you want to logout?","41":"Yes","42":"No","43":"Edit Profile","44":"Joined on","45":"Save Changes","46":"Delete Account","47":"Find your desire\nhealth solution","48":"Search doctor, drugs, articles...","49":"General","50":"Lungs Prob","51":"Dentist","52":"Psychiatrist","53":"Covid","54":"Cardiologist","55":"Early protection for\nyour family health","56":"Learn More","57":"Top Doctor","58":"See all","59":"Book Appointment","60":"Find Doctor","61":"Recommended Doctors","62":"Email","63":"Enter your email, we will send you a confirmation link" ,"64":"HealthHub revolutionizes appointment scheduling by providing a user-friendly platform for patients to easily find and book appointments with healthcare professionals based on specialty, location, and availability. It eliminates the hassle of long wait times and phone calls, making it simple to manage healthcare schedules and stay connected with medical providers" , "65":"Enter about information"}
  };
}

class MyLocaleAr extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {"1": "الصفحة الرئيسية", "2": "حول", "3": "الإعدادات" ,"4":"الوضع المظلم" , "5":"اللغات" , "6":"الملف الشخصي" , "7":"التوفر" , "8":" جميع المواعيد " ,"9":"خروج" ,"10":"تحديث" , "11":"العنوان" , "12":"هاتف" ,"13":"الاسم الكامل" , "14":"توفر اليوم" ,"15":"إضافة موعد" ,"16":"ساعات مختارة" ,"17":"اليوم المختار","18":"تسجيل الدخول" ,"19":"أدخل بريدك الإلكتروني" , "20":"ادخل رقمك السري","21":"نسيت كلمة السر؟" , "22":"ليس لديك حساب؟" , "23":"اشتراك" , "24":"أدخل هاتفك" , "25":"أدخل عنوانك" , "26":"أدخل تخصصك" , "27":"أدخل اسمك الكامل" , "28":"هل لديك حساب؟" , "29":"إنشاء حساب" , "30":"إعادة تعيين كلمة المرور" , "31":"قم بتسجيل الدخول للاستمتاع بالميزات التي قدمناها \nوالبقاء في صحة جيدة" , "32":"هيا بنا نبدأ!" ,  "33":"توفر غدا" , "34":"تاريخ" , "35":"ساعة" ,"36":"الاسم " ,"37":"البريد  " ,"38":"هاتف المريض" , "39":"مواعيد اليوم","39":"تحديث الملف","40":"هل أنت متأكد أنك تريد تسجيل الخروج؟","41":"نعم","42":"لا","43":"تعديل الملف الشخصي","44":"انضم يوم","45":"حفظ التغييرات","46":"حذف الحساب","47":"ابحث عن\nالحل الصحي الذي تريده","48":"بحث الطبيب والأدوية والمقالات ...","49":"عام","50":"مشكلة الرئتين","51":"طبيب أسنان","52":"طبيب نفسي","53":"مرض فيروس كورونا","54":"طبيب القلب","55":"الحماية المبكرة\n لصحة عائلتك","56":"تعلم أكثر","57":"طبيب أعلى","58":"اظهار الكل","59":"تحديد موعد","60":"ابحث عن الطبيب","61":"الأطباء الموصى بهم","62":"بريد إلكتروني","63":"أدخل بريدك الإلكتروني، وسوف نرسل لك رابط التأكيد" ,"64":"يُحدث HealthHub ثورة في جدولة المواعيد من خلال توفير منصة سهلة الاستخدام للمرضى للعثور بسهولة على المواعيد وحجزها مع متخصصي الرعاية الصحية بناءً على التخصص والموقع والتوافر. إنه يزيل متاعب أوقات الانتظار الطويلة والمكالمات الهاتفية، مما يجعل من السهل إدارة جداول الرعاية الصحية والبقاء على اتصال مع مقدمي الخدمات الطبية." , "65":"أدخل حول المعلومات"}
  };
}

class MyLocaleFr extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "fr": {"1": "Accueil", "2": "Sur", "3": "Paramètres" , "4":"Mode sombre" , "5":"Langues" , "6":"Profile" , "7":"Disponibilité" , "8":" Tous les rendez-vous" , "9":"Déconnecter","10":"Mettre à jour" ,"11":"adresse" ,"12":"Téléphone" ,"13":"Nom et prénom" , "14":"Disponibilité d'aujourd'hui" ,"15":"Ajouter un rendez-vous" , "16":"Heures sélectionnées" ,"17":"Jour sélectionné" ,"18":"Se connecter" , "19":"Entrer votre Email" , "20":"Entrer  votre mot de passe" , "21":"Mot de passe oublié?" , "22":"Vous n'avez pas de compte ?"  , "23":"S'inscrire" , "24":"Entrez votre téléphone" , "25":"Entrer votre adresse" , "26":"Entrez votre spécialité" , "27":"Entrez votre nom complet" , "28":"Vous avez déjà un compte?" , "29":"Créer un compte" , "30":"réinitialiser le mot de passe" , "31":"Connectez-vous pour profiter des fonctionnalités que nous avons \nfournies et rester en bonne santé" , "32":"Commençons!" , "33":"Disponibilité de demain" , "34":"Date" , "35":"Heure" , "36":"Nom complet du patient" ,"37":"E-mail" ,"38":"Téléphone du patient" , "39":"Rendez-vous d'aujourd'hui","40":"Êtes-vous sûr de vouloir vous déconnecter?","41":"Oui","42":"Non","43":"Editer le profil","44":"Rejoint le","45":"Sauvegarder les modifications","46":"Supprimer le compte","47":"Trouvez la solution\nsanté de votre choix","48":"Rechercher médecin, médicaments, articles...","49":"Générale","50":"Poumons Prob","51":"Dentiste","52":"Psychiatre","53":"Covid","54":"Cardiologue","55":"Protection précoce pour la santé de votre famille","56":"Apprendre encore plus","57":"Meilleur docteur","58":"Voir tout","59":"prendre rendez-vous","60":"Trouver un médecin","61":"Médecins recommandés","62":"email","63":"Entrez votre email, nous vous enverrons un lien de confirmation" , "64":"HealthHub révolutionne la planification des rendez-vous en fournissant une plateforme conviviale permettant aux patients de trouver et de prendre facilement des rendez-vous avec des professionnels de la santé en fonction de la spécialité, de l'emplacement et de la disponibilité. Il élimine les tracas liés aux longs temps d'attente et aux appels téléphoniques, ce qui simplifie la gestion des horaires de soins et le maintien du contact avec les prestataires médicaux" , "65":"Entrez les informations"}
  };
}
